qcode-software/qcode-tcl

- doc/global-json-response.md
- doc/index.md
- doc/procs/action_redirect.md
- doc/procs/message_alert.md
- doc/procs/message_error.md
- doc/procs/message_notify.md
- doc/procs/record_all_valid.md
- doc/procs/record_invalid.md
- doc/procs/record_remove.md
- doc/procs/record_valid.md
- doc/response_api.md
- tcl/actions.tcl
- tcl/message.tcl
- tcl/record.tcl
Moving over the global JSON response implementation from the blog project to the Qcode-tcl library.
> JSON Response Files And Docs

- doc/procs/conn_path.md
- doc/procs/conn_url.md
- doc/procs/is_uri_valid.md
- tcl/conn.tcl
- tcl/error.tcl
- tcl/url.tcl
> Conn path encoding

- doc/procs/is-decimal.md
- tcl/cast.tcl
- tcl/check.tcl
- tcl/conn.tcl
- tcl/filter.tcl
- tcl/format.tcl
- tcl/html_table.tcl
- tcl/is.tcl
- tcl/return.tcl
- tcl/sql.tcl
- tcl/style.tcl
- tcl/table.tcl
- tcl/tson.tcl
- tcl/url.tcl
- tcl/util.tcl
- test/cast.test
- test/is.test
* Updated occurrences of `is_x` calls to use the ensemble `qc::is x`.
* Updated `qc::is decimal` to account for precision and scale arguments.
* Updated and added tests.
* Tests all passed except crypt.test and db.test which didn't run due to missing package `pgtcl`.
> is_x -> qc::is x

- tcl/cast.tcl
- tcl/conn.tcl
- tcl/cookie.tcl
- tcl/date.tcl
- tcl/format_date.tcl
- tcl/format_timestamp.tcl
- tcl/is.tcl
- tcl/math.tcl
- tcl/schedule.tcl
- tcl/session.tcl
- tcl/util.tcl
- test/cast.test
- test/format_timestamp.test
* Updated all `cast_x` to use ensemble `qc::cast x`
* Fixed bug with `qc::cast decimal`
* Exported `qc::cast epoch` as it's used by many other procedures.
* Updated, added, and run tests. All tests passed.
> cast_x -> qc::cast x

- tcl/cast.tcl
`qc::cast domain` will now try to cast the given value to base type where possible.
> Cast to domain base type where possible for qc::cast domain

- tcl/handlers.tcl
- tcl/register.tcl
- tcl/util.tcl
- Various small unit tests on `qc::path_best_match` and `qc::path_variables`
- Usual testing on dev blog with refactored `qc::handlers` (create/delete/restore posts/pages/comments, browse pages, log in/out etc.)
> Handlers refactored.

- doc/procs/return_response.md
- tcl/conn.tcl
- tcl/filter.tcl
- tcl/return.tcl
As discussed in #165 
Checklist
------------
> Rename: return_result > return_response

- doc/handlers-api.md
- doc/index.md
- doc/procs/handlers-call.md
- doc/procs/handlers-exists.md
- doc/procs/handlers-validate2model.md
- doc/procs/handlers-validation-call.md
- doc/procs/handlers-validation-exists.md
Documentation for the `qc::handlers` API.
> Handlers API Documentation

- doc/connection-handlers.md
- doc/index.md
- doc/procs/handler_db_files.md
- doc/procs/handler_files.md
- doc/procs/handler_restful.md
Documentation for the connection handlers outlining the three that are available, what they do, and how they might be used.
> Connection handler docs

- doc/data-model-dependencies.md
- doc/index.md
This document outlines the dependencies in the data model for the qcode-tcl library broken down by proc. There are likely a few that are missing but I've added the most obvious from my experience and perusing of the library.
> Docs: Data Model Dependencies

- doc/index.md
- doc/setting-up.md
This document pulls together parts of the new transaction process to form a small guide on using the parts together.
> Docs: Setting Up

- tcl/email.tcl
- tcl/excel.tcl
Requires:
```
sudo apt-get install libexcel-writer-xlsx-perl
```
> xlsx support

- tcl/form.tcl
Checklist
----
- No method given
- `method GET` given as args
> Don't overload GET method

- tcl/url.tcl
- test/url.test
> New proc url_make, and extend url_parts

- tcl/auth.tcl
- tcl/filter.tcl
- tcl/session.tcl
> EOD commit

- tcl/is.tcl
- tcl/url.tcl
- test/url.test
> Extend url_parts to handle empty components

- tcl/cast.tcl
- tcl/is.tcl
Not ready for merge just a pull request to remind me about these changes
> Tradecomms

- tcl/form_db.tcl
Testing
---------
Tested with mla-erp new sales order.
> Authenticity token added to form_db

- tcl/handlers.tcl
- tcl/register.tcl
- tcl/util.tcl
- tcl/util_list.tcl
Tcl
----
- Used the following test pages with varying input
```tcl
register GET /test1.html {form.foo} {
set list [list]
lappend list "FOO: $foo"
lappend list "FORM.FOO: ${form.foo}"
lappend list "LOCAL VARS: [info locals]"
return_html [html_list $list]
}
register GET /test2.html {form.foo form.bar} {
lappend list "FOO: $foo"
lappend list "FORM.FOO: ${form.foo}"
lappend list "BAR: $bar"
lappend list "FORM.BAR: ${form.bar}"
lappend list "LOCAL VARS: [info locals]"
return_html [html_list $list]
}
register GET /test3.html {form.foo form.bar baz} {
lappend list "FOO: $foo"
lappend list "FORM.FOO: ${form.foo}"
lappend list "BAR: $bar"
lappend list "FORM.BAR: ${form.bar}"
lappend list "BAZ: $baz"
lappend list "LOCAL VARS: [info locals]"
return_html [html_list $list]
}
register GET /test4.html …
```
> Register qualified args

- tcl/http.tcl
- test/http.test
Checklist
----
- Unit tested:
- `qc::http_header_parse`
- Simple input e.g. `"Connection" "keep-alive"`
- Complex input e.g. `"Accept" "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"`
- Special case input e.g. `"Cookie" "_gat=1;logged_in=yes;tz=Europe%2FLondon"`
- `qc::http_header_sort_values_by_weight`
- With q values
- Without q values
- Mixture of with and without q values
- Tested in MLA ERP:
- `qc::http_header_get`
- Get various headers from the request response:
```tcl
register GET /cn.html {} {
#| Testing content negotiation
qc::return2client html [qc::http_header_get "Accept"]
}
```
- Try to get non-existent headers e.g. `qc::http_header_get "FOO"`
- `qc::http_accept_header_best_mime_type`
- Specifying different available media types:
```tcl
register …
```
> Content negotiation v1

- tcl/error.tcl
- tcl/http.tcl
Tcl
----
- Tested with MLA ERP changes.
- Various errors and return types tested .
- Content negotiation tested through setting up test URL handlers with different suffixes.
> Error handler content negotiate

- tcl/perm.tcl
Checklist
----
- Tested with various return codes
- Tested then and else clauses
- Tested with loops
```tcl
proc test {} {
qc::perm_if sales_order write {
log "perm_if THEN"
return
} else {
log "perm_if ELSE"
return "testing"
}
log "after perm_if"
}
proc test2 {} {
foreach item {foo bar baz} {
qc::perm_if sales_order write {
log "perm_if THEN"
break
} else {
log "perm_if ELSE"
return "testing"
}
log "after perm_if"
}
log "after loop"
}
```
> On appropriate return codes return in parent stack frame

- tcl/filter.tcl
[MLA issue #832](https://github.com/qcode-software/mla-www/issues/832#issuecomment-121573933)
> Always log in the anonymous user in no session

- doc/global-json-response.md
- doc/procs/response_extend.md
- doc/response_api.md
- tcl/ensemble_handlers.tcl
- tcl/json.tcl
- tcl/response.tcl
- tcl/tson.tcl
Tcl
----
- With `extend` and without extend keyword to make sure mapping worked.
- A single key value pair
- Multiple key value pairs
- Missing keys or values
> JSON response extend

- doc/procs/url.md
- tcl/url.tcl
- test/url.test
Tcl
----
- Colon vars in path and fragment.
- Overwriting existing form variables.
- Tilde args i.e. `qc::args foo.html ~ foo bar baz`
- Only path, only file, full URL e.g.:
- `qc::url file.html foo 123 bar 456`
- `qc::url /:foo/bar foo 123`
- `qc::url http://www.qcode.co.uk/:foo#:fragment foo 123 fragment test bar 456`
> qc::url update

- tcl/url.tcl
- test/url.test
Tcl
----
- Ran test suite with new tests that test `qc::url` with an already encoded URL.
- Navigated known problematic URLs in mla-erp.
> Url parts decode

- tcl/url.tcl
- test/url.test
Tcl
----
- URL test suite with new tests written for colon variable errors.
- Browsing some elements of mla-erp known to use URL e.g. product select table, report drill downs...
> Error on key missing or colon var value begins with colon

- tcl/filter.tcl
- tcl/form_db.tcl
- tcl/session.tcl
Tcl
----
- Tested with MLA ERP with header, without header, and with both header and form variable.
> Centralise authenticity token

- tcl/error.tcl
- tcl/filter.tcl
- tcl/html.tcl
- tcl/json.tcl
- tcl/return.tcl
Tcl
----
- Tested on MLA ERP DEV:
- `/sales_order_select.html` form - entering invalid and valid data.
- Entering invalid values for query string params in URLs i.e. `/sales_order.html?sales_order_id=foo`
> Filter validate get update

- tcl/html.tcl
Add support for variable pagesizes and -nomargin option.
> Additional options for html2pdf to support label printing

- tcl/html_table.tcl
- test/html_table.test
Do https://github.com/qcode-software/qcode-tcl/pull/292 first
> Html table tfoot data

- tcl/filter.tcl
- tcl/handlers.tcl
Do not merge! Requires discussion first.
> Handler validation cast

- tcl/db.tcl
- tcl/db_introspection.tcl
db_introspection.tcl
Added introspection commands db_owner, db_database_name, db_user
db.tcl
Updated db_get_handle command
> Added introspection commands and updated db_get_handle

- tcl/db_init.tcl
- tcl/db_introspection.tcl
1. Created db_init proc to initialise the database objects required for qcode-tcl
2. Added db_extension_exists command to db_introspection.tcl
> Added db_extension_exists command and db_init.tcl

- tcl/validate.tcl
@bvw Can you please take a look over this bug fix please ?
For David's form validation was producing a hard error when it came to checking "check" constraints because result of data type checking was false.
Can we also get Nicky to look over this and do some testing for us ... got other things to work on with David so would be good to get someone else to do more testing.
> bug fix for check constraints where data type checking has failed

- tcl/cast.tcl
- tcl/castable.tcl
- tcl/is.tcl
- test/is.test
> Added url_path into Tcl ensemble

- tcl/bs_capsule.tcl
- tcl/bs_form_layout.tcl
> Added bootstrap capsule widgets and form layout

- tcl/up.tcl
> Restrict Var Names

- tcl/filter.tcl
> HTTP Request Validation Filter Added

- tcl/filter.tcl
> New Filter to Check Form Variable Names

- tcl/db.tcl
- tcl/db_cache.tcl
Ran tests described in first post of #361 
rows_returned_by_qry | time (m:s)
------------------------------|-------------
10 | 0:0.052
100 | 0:0.002
1000 | 0:0.022
10000 | 0:0.225
25000 | 0:0.565
50000 | 0:1.141
75000 | 0:1.697
100000 | 0:2.265
rows_returned_by_qry | time (m:s)
------------------------------|-------------
10 | 0:0.0
100 | 0:0.002
1000 | 0:0.023
10000 | 0:0.225
25000 | 0:0.568
50000 | 0:1.148
75000 | 0:1.728
100000 | 0:2.301
> db_foreach Optimisation

- tcl/db.tcl
- tcl/db_cache.tcl
> unset result

- tcl/util.tcl
> proc to memoize if possible

- tcl/sql.tcl
- test/sql.test
- Tests run sucessfully
- Tested a report with sql_sort on mla_erp DEV
- Audited mla-erp code for unusual usage of sql_sort, nothing found.
> Improve sql-injection protection for sql_sort

- tcl/is.tcl
- test/is.test
Bug Report: https://github.com/qcode-software/tlc/issues/672
Tested on dev
> relax is_url check to allow & in path segments as per rfc 3986

- doc/data-model-dependencies.md
- doc/db.md
- doc/procs/db_database_name.md
- doc/procs/db_extension_exists.md
- doc/procs/db_init.md
- doc/procs/db_owner.md
- doc/procs/db_sequence_exists.md
- doc/procs/db_user.md
- doc/procs/db_user_is_superuser.md
Added documentation for database initialisation and introspection procs.
> Database Documentation

- tcl/csv.tcl
- tcl/db.tcl
For discussion:
Two tools to help bulk loading of data without attempting to hold all  the data in memory.
> pg_copy_load & csv_file_foreach

- tcl/tson.tcl
```tcl
set tson [list object \
customer_ref [list string "ABCDEF"] \
delivery_address [list object \
delivery_name "null" \
delivery_company_name [list string "Qcode Software"] \
delivery_address1 [list string "Clark Thomson Building"] \
delivery_address2 [list string "Fairways Business Park"] \
delivery_town [list string "Inverness"] \
delivery_county "null" \
delivery_country_code [list string "GB"] \
delivery_postcode [list string "IV2 6AA"] \
delivery_telephone "null"] \
products [list array \
[list object \
product_code [list string "ABC"] \
quantity 20] \
[list object \
product_code [list string "DEF"] \
quantity 1]]]
```
---
Test:
```tcl
qc::tson_exists $tson customer_ref
```
Output:
```
t
```
---
Test:
```tcl
qc::tson_exists $tson delivery_address
```
Output:
```
t
```
---
Test: …
> TSON Exists

- tcl/cast.tcl
Test:
```tcl
qc::cast_value2model web_order.delivery_method deliver
```
Output:
```
DELIVER
```
---
Test:
```tcl
qc::cast_value2model web_order.delivery_method abc
```
Output:
```
"abc" is not a valid value for enum "delivery_method".
```
---
Test:
```tcl
qc::cast_value2model web_order.order_id 1
```
Output:
```
1
```
---
Test:
```tcl
qc::cast_value2model web_order.order_id a
```
Output:
```
"a" is not a valid integer. It must be a number between -2147483648 and 2147483647.
```
---
Test:
```tcl
qc::cast_value2model web_order.delivery_method ""
```
Output:
```
delivery_method cannot be empty.
```
> Proc to Cast a Single Value to the Data Model

- tcl/tson.tcl
Test:
```tcl
qc::tson_array_foreach element [list array 1 2 3 4 5] {
puts $element
}
```
Output:
```
1
2
3
4
5
```
Test:
```tcl
qc::tson_array_foreach element [list array 1 2 3 4 5] {
if { $element % 2 == 0 } {
continue
} else {
puts $element
}
}
```
Output:
```
1
3
5
```
Test:
```tcl
qc::tson_array_foreach element [list array 1 2 3 4 5] {
return $element
}
```
Output:
```
1
```
Test:
```tcl
qc::tson_array_foreach element [list array 1 2 3 4 5] {
if { $element == 3 } {
break
} else {
puts $element
}
}
```
Output:
```
1
2
```
> Added tson_array_foreach Procedure

- test/http.test
> Fixed a bug with http_head test.

- tcl/image_file.tcl
Testing
----
- Cleared image cache on DEV and restarted server
- Navigated between several image-heavy pages,
- Confirmed that pages loaded faster once cache had been created
> Performance refinement for image cache

- README.md
- doc/installation.md
- doc/tutorial-2-form-posting-and-nsv-variables.md
- Created second tutorial - an intro to forms
- Added link to readme for tutorial 2
- Minor amend to title of installation / introduction tutorial
> Paul tutorials two forms

- tcl/http.tcl
port qcode-tcl-5 change into master
> qc::http_get support for valid_response_codes option

- tcl/file.tcl
> Add support for binary flag in file_temp and file_write

- tcl/cast.tcl
- tcl/db_introspection.tcl
- tcl/sql.tcl
- tcl/validate.tcl
Testing
----
- Load www on DEV, connecting to mla db as mla_www user, with data in mla_www schema
- View product
- Add product to order
- Update order details
- Place order
- Provide feedback
- Log in to erp on DEV
- View product on erp
> Schema introspection polymorphic

- tcl/error.tcl
- tcl/util.tcl
> Qcode 5 backporting

- tcl/cast.tcl
- tcl/handler.tcl
- tcl/handlers.tcl
- tcl/register.tcl
Handler procs.
Basic test of adding a restful URL to ERP, adding an ERP equivalent of ```td_handler```, and checking it was accessible and that variables were validated against the data model.
> handler support

- tcl/db.tcl
- tcl/image_file.tcl
- tcl/image_filesystem_cache.tcl
> Qcode 5 backporting2

- tcl/session.tcl
> session_purge update

- tcl/http.tcl
- tcl/oauth2.tcl
Tcl
----
Testing
---
- `qc::http_post`
- OAuth 2 procs
- Tested with various optional arguments.
> oAuth2 implementation

- tcl/http.tcl
Tcl
----
Testing
---
- Tested against an API:
> Allow user to request response headers and code from http_get

- tcl/tabular_text.tcl
- tcl/util.tcl
- test/castable.test
- test/tabular_text.test
- test/util.test
tools to parse tabular text
NOT ready for merge ... needs more TCL tests.
> tools to parse tabular text

- tcl/http.tcl
Tested with `sudo make test VERSION=8.24.3`
> Add additional iana mappings

- tcl/handlers.tcl
- tcl/register.tcl
Testing
---
- Run the following via control port:
> Optimise Handlers NSV Array by Flattening Structure

- tcl/tabular_text.tcl
- test/tabular_text.test
Adds `trim false` and `true` to columns conf.
E.G.
```tcl
lappend columns_conf [list label "Column A" var_name col_a trim false]
```
> tabular_text_parse trim option

- tcl/cast.tcl
- tcl/castable.tcl
- tcl/db_file.tcl
- tcl/handlers.tcl
- tcl/http.tcl
- tcl/is.tcl
- tcl/multimap.tcl
- tcl/oauth2.tcl
- tcl/register.tcl
- tcl/util.tcl
- tcl/widget.tcl
backport latest changes to qcode-tcl-5
> backporting changes to qcode-tcl

- tcl/form_db.tcl
Final difference between master and qcode-tcl-5
> add qc::form_authenticity_token to form_db

- tcl/is.tcl
- test/http.test
> qc::is mobile_number updates

- tcl/soap.tcl
- test/soap.test
Added test and removed hardcoded tabs
> added soap template test

- tcl/user_agent.tcl
- test/user_agent.test
- user_agent_parse proc
- user_agent_parse test
Tested with the tcltest
> user_agent_parse and tests

- tcl/image_file.tcl
> Improve quality of webp images

- tcl/cookie.tcl
> preserve existing cookie behaviour

- doc/cgi-example-tcl.md
- doc/cgi-get-example-tcl.md
- doc/naviserver-config-cgi.md
- doc/naviserver-introduction.md
- package.tcl
- pkg_mkIndex
- tcl/ssh.tcl
Allow builds on platforms which do not run tclsh8.5
> Allow use of >tclsh8.5

- tcl/db_file.tcl
- tcl/email.tcl
- tcl/image_file.tcl
- tcl/session.tcl
- test/s3_tools.test
Changes made to qcode-tcl-10 merged to master
> UUID wrapper

- tcl/dict.tcl
- test/dict_intersect.test
- test/dict_is_subset.test
> New APIS - dict_intersect & dict_is_subset

- tcl/db_file.tcl
- test/db_file_setup.tcl
> db_file API updates

- tcl/db_file.tcl
> Bug fix to delete the tmp file after it is migrated to s3

- tcl/tabular_text.tcl
- test/tabular_text.test
Add optional casting to tabular text parse
> Add optional casting to tabular text parse

- tcl/conn.tcl
- tcl/response.tcl
- tcl/return.tcl
These lines were using hex c2a0 (non-breaking space) instead of hex 20 spaces. Probably a paste error.
> Remove non-breaking spaces

- tcl/is.tcl
- test/is.test
> Add qc::is html

- test/all.tcl
Standardise all.tcl TCLtest
READY for merge
> Standardise all.tcl TCLtest

- tcl/dicts_diff_any.tcl
- tcl/ldicts_diff_any.tcl
- test/dicts_diff_any.test
- test/ldicts_diff_any.test
port dict diff tools to qcode-tcl
READY for merge
> port dict diff tools to qcode-tcl

- tcl/db.tcl
- tcl/db_trans.tcl
- test/db.test
- test/db_setup.tcl
READY for merge
found small bug in db_trans but it's never caused issue since we have only ever used 1 default db pool.
> db_trans isolation using alt db handle

- test/db_introspection.test
```
Tests ended at Tue Jan 25 14:59:48 GMT 2022
all.tcl:	Total	1726	Passed	1713	Skipped	13	Failed	0
12	knownBug
Total	1726	Passed	1713	Skipped	13	Failed	0
```
> db introspection tests

- tcl/cast.tcl
- tcl/castable.tcl
- tcl/is.tcl
- tcl/response.tcl
- tcl/return.tcl
- test/cast.test
- test/is.test
- test/response_login.test
- test/response_redirect.test
- test/return_next.test
> New type next_url

- tcl/http.tcl
> Add iana windows-1250 mapping

- tcl/http.tcl
- test/http.test
Testing
---
```
tclsh http.test
http.test:	Total	24	Passed	24	Skipped	0	Failed	0
```
> Added http_patch Proc to Make HTTP PATCH Requests

- tcl/http.tcl
- test/http.test
Testing
---
```
tclsh http.test
http.test:	Total	25	Passed	25	Skipped	0	Failed	0
```
> Add Options to Return Response Code and Headers to http_patch

- tcl/_s3.tcl
- tcl/s3.tcl
- test/s3.test
```
Tests ended at Wed Jun 08 16:19:36 BST 2022
all.tcl:	Total	1817	Passed	1804	Skipped	13	Failed	0
12	knownBug
Total	1817	Passed	1804	Skipped	13	Failed	0
```
> Add S3 exists proc

- tcl/_s3.tcl
- test/_s3.test
- test/s3.test
```
Tests ended at Fri Jun 10 11:25:56 BST 2022
all.tcl:	Total	1820	Passed	1807	Skipped	13	Failed	0
12	knownBug
Total	1820	Passed	1807	Skipped	13	Failed	0
```
> Use regional s3 endpoint

- tcl/widget.tcl
- test/widget.test
Adds new datalist widget
__Example__
> Datalist widget

- tcl/html_table.tcl
- test/html_table.test
> Html table col tfoot

- test/s3.test
> Fix failing s3 test

- tcl/math.tcl
- test/math.test
Add support for decimal arithmetic division
READY for merge
> Support for decimal arithmetic division

- tcl/file.tcl
> Lock File Chunk Upload per User

- Makefile
Release Type: ( MAJOR | MINOR | PATCH )
-------------
(PATCH)
Description
--------------
* Auto testing runs from a different directory than was assumed in some of the tests.
> run tests from repo root

- test/http.test
Without docker active:
```
$ tclsh test/http.test 
http.test:	Total	28	Passed	18	Skipped	10	Failed	0
10	httpbin_running
```
With docker active:
```
$ tclsh test/http.test 
Docker installed...
Image kennethreitz/httpbin:latest present...
httpbin not running - starting...
Shutting down httpbin...
http.test:	Total	28	Passed	28	Skipped	0	Failed	0
```
Tests all
```
Tests ended at Fri Apr 28 16:04:57 BST 2023
all.tcl:	Total	1864	Passed	1851	Skipped	13	Failed	0
Sourced 81 Test Files.
12	knownBug
Total	1864	Passed	1851	Skipped	13	Failed	0
Sourced 81 Test Files.
```
> use httpbin docker container where possible

- .github/workflows/pull-request-linting.yml
- tcl/aws.tcl
- test/aws.test
Tests avoiding the httpbin timeouts
```
Tests located in:  /home/david/qcode-tcl/test
Tests running in:  /home/david/qcode-tcl
Temporary files stored in /home/david/qcode-tcl
Tests began at Fri Apr 28 16:54:47 BST 2023
_s3.test
args.test
auth.test
aws.test
aws_s3_ls.test
aws_s3_rest_api.test
aws_s3_s3_uri_parse.test
aws_s3_xml.test
binary_convert.test
cast.test
castable.test
check.test
conn.test
conn_host.test
conn_location.test
conn_port.test
conn_protocol.test
conn_remote_ip.test
cookie.test
crypt.test
css_selector2xpath.test
csv.test
date.test
db.test
db_file.test
writing /tmp/HkCKJcoEog ... …
```
> Unit tests for AWS procs & IMDSv2

- Makefile
Upload to both apt repos for the interim
> repo name change

- Makefile
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Full test of autorelease action
> Bump version minor version

- Makefile
- package.tcl
- pkg_mkIndex
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
Tested by copying the `qcode-tcl/tcl/*` to `/tmp/test` and running:
```
./package.tcl /tmp/test package qcode 99.99.99
./pkg_mkIndex package qcode 99.99.99
mkdir -p /usr/lib/tcltk/qcode99.99.99
cp -r package/* /usr/lib/tcltk/qcode99.99.99/
tclsh
package require qcode
info procs qc::is::*
info procs qc::is_*
```
> Include Tcl Files in Subdirectories in the Tcl Package

- tcl/reload.tcl
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
Sourced `qcode-tcl/tcl/reload.tcl` in `mla_erp` dev, and ran `reload`
> Use glob_recursive in reload

- tcl/util.tcl
- test/util.test
Board Ticket #
--------------
[Refactor tlc/erp tlc/www tlc/lib to comply with linter. #7712](https://github.com/qcode-software/tlc/issues/7712)
--------------
(MINOR)
Description
--------------
New Utility API
Test Results
--------------
> New Utility API

- tcl/qc/is/url.tcl
- test/is.test
Board Ticket #
--------------
https://github.com/qcode-software/tlc/issues/7960
--------------
(MINOR)
Description
--------------
allow ";" in urls
Test Results
--------------
> allow ";" in urls

- Makefile
Board Ticket #
--------------
https://github.com/qcode-software/qcode/issues/70
https://github.com/qcode-software/tlc/issues/7530
--------------
(MINOR)
Description
--------------
deb.qcode.co.uk is being decommissioned so references and uses are being removed.
Test Results
--------------
N/A
> Remove Upload to deb.qcode.co.uk from Makefile

- doc/naviserver-introduction.md
Board Ticket #
--------------
https://github.com/qcode-software/qcode/issues/70
https://github.com/qcode-software/tlc/issues/7530
--------------
(PATCH)
Description
--------------
deb.qcode.co.uk is being decommissioned so references and uses are being removed.
Test Results
--------------
N/A
> Update Naviserver Documentation

- tcl/qc/aws/s3/rest_api.tcl
Board Ticket #
--------------
--------------
(PATCH)
Description
--------------
Test Results
--------------
```
tclsh test/all.tcl
Tests located in:  /home/nick/qcode-tcl/test
Tests running in:  /home/nick/qcode-tcl
Temporary files stored in /home/nick/qcode-tcl
Tests began at Mon Mar 04 16:32:39 GMT 2024
_s3.test
args.test
auth.test
aws.test
aws_metadata.test
aws_s3_ls.test
aws_s3_rest_api.test
aws_s3_s3_uri_parse.test
aws_s3_sigv4_headers.test
aws_s3_xml.test
binary_convert.test
cast.test
castable.test
check.test
conn.test
conn_host.test …
```
> Only Accept HTTP Code 200 Responses in qc::aws s3 rest_api http_get

- tcl/http.tcl
- test/http.test
- test/http_header_encoding.test
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/5688
--------------
(MINOR)
Description
--------------
https_header_encoding updates
Test Results
--------------
> https_header_encoding updates

- tcl/url.tcl
- test/url.test
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
url_make updates
Test Results
--------------
> url_make updates

- Makefile
Board Ticket #
--------------
https://github.com/qcode-software/tlc/issues/8532
--------------
(MINOR)
Description
--------------
Copy package to bookworm distribution from buster.
Test Results
--------------
> Add to bookworm dist

- tcl/handlers.tcl
- test/handlers.test
Board Ticket #
--------------
https://github.com/qcode-software/tlc/issues/9376
--------------
(MINOR)
Description
--------------
qc::handlers::exists fix
Test Results
--------------
> qc::handlers::exists fix

- tcl/http.tcl
- test/http.test
Board Ticket #
--------------
* https://github.com/qcode-software/tlc/issues/9429
--------------
(MINOR)
Description
--------------
```qc::http_save``` can optionally follow redirects
Test Results
--------------
```
Total   1893    Passed  1880    Skipped 13      Failed  0
Sourced 87 Test Files.
```
> Http save follow location

- actions/tcl-module-debian-package-upload/action.yml
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/6017
--------------
(PATCH)
Description
--------------
Add ssh-keyscan
Test Results
--------------
> Add ssh-keyscan

- actions/tcl-module-debian-package-upload/action.yml
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
> Explicitly specify identity key

- actions/tcl-module-debian-package-upload/action.yml
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
> Debian package upload bug fix

- tcl/xml.tcl
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
> white space

- .github/workflows/release.yml
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
> Version bug fix

- tcl/session.tcl
- test/session.test
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
```
Running TCL Tests in /home/nick/qcode-tcl/test/session.test ...
session.test:	Total	1	Passed	1	Skipped	0	Failed	0
Finished running TCL Tests in /home/nick/qcode-tcl/test/session.test
```
> Set global session_id when creating a session in session_new

- tcl/session.tcl
- test/session.test
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test Results
--------------
```
Running TCL Tests in /home/nick/qcode-tcl/test/session.test ...
session.test:	Total	2	Passed	2	Skipped	0	Failed	0
Finished running TCL Tests in /home/nick/qcode-tcl/test/session.test
```
> Remove login from qc::session_new and added new proc qc::session_new_and_login

- tcl/qc/is/safe_html.tcl
- test/is.test
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Test case currently fails under tdom=0.9.3-1
Passes with tdom=0.9.1-1
Test Results
--------------
> test case addition

- .github/workflows/release.yml
- tcl/_s3.tcl
- test/s3.test
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/6192
--------------
(MINOR)
Description
--------------
Add encryption to s3 get/put APIs
Test Results
--------------
> Add encryption to s3 get/put APIs

- actions/tcl-module-build/action.yml
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/6165
--------------
(MINOR)
Description
--------------
Sort tcl files while creating the module
Test Results
--------------
> Sort tcl files while creating the module

- tcl/s3.tcl
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/6192
--------------
(MINOR)
Description
--------------
Update qc::s3 to match mla_s3
Test Results
--------------
> Update qc::s3 to match mla_s3

- tcl/s3.tcl
- test/s3.test
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/6192
--------------
(MINOR)
Description
--------------
Standardise s3::head and s3::exists commands
Test Results
--------------
> Standardise s3::head and s3::exists commands
