qcode-software/qcode-tcl

tcl/conn.tcl, tcl/filter.tcl, tcl/handlers.tcl, tcl/nsv_dict.tcl, tcl/register.tcl, tcl/util.tcl
* `register` now allows for registering of paths i.e. `register GET /page`
* `qc::handlers` updated to choose a match with the least amount of colon variables
* `lappend` added to `qc::nsv_dict`
=> Register paths fix

doc/procs/anonymous_session_id.md, doc/procs/anonymous_user_id.md, tcl/session.tcl
While reviewing documentation and what was left to cover I discovered that `anonymous_session_id` and `anonymous_user_id` hadn't been migrated yet.
Migrated the procs and added documentation.
Checklist
----
- Tested on dev blog to make sure everything still worked
=> Anonymous session migrate

doc/procs/cast-safe_html.md, tcl/cast.tcl
This change is to fix a bug that makes safe HTML unsafe due to casting to XML. One particular instance was that casting to XML causes tags with no content between them to be void elements i.e. self-closing when they aren't supposed to be. This can cause problems of HTML breaking out of its container when used in particular cases.
For example:
```
% set html {<a href="test"></a>}
<a href="test"></a>
% qc::cast safe_html $html
<a href="test" />
```
The `a` tag is not a void element so shouldn't self-close as per w3 documentation: http://www.w3.org/TR/html-markup/syntax.html#syntax-elements
Checklist
------------
- Testing done as changed in documentation plus a few other invalid and valid HTML snippets. All passed OK.
=> qc::cast safe_html no longer casts to xml

tcl/return.tcl
@PeterChaplin could you take a look at the changes below and merge if you think they are ok ?
1. added option to specify whether the payload should be downloaded or displayed in the browser.
This allows you to either display PDF (or .csv, .txt, xlsx etc) files in a browser or have the browser give the user the option to save it to disk.
2. Changed the code to use ns_returnfile as reading binary PDFs and using ns_return didn't seem to work for me.
=> refactored code

tcl/auth.tcl, tcl/filter.tcl, tcl/session.tcl
The current user ID was not being set up if the session was recognised as valid. Changed to set the current user ID.
`qc::auth_session` changed to check validity of session rather than existence.
----
- Tested change on blog project. All working as expected.
=> Filter authenticate update

tcl/filter.tcl
Noticed a bug under certain circumstances whereby `qc::auth` would fail if the user session was invalid. The anonymous session ID is set if the session was invalid however `qc::auth` grabs the session ID from the cookie which is the old invalid one because the user agent hasn't yet been told to update the cookie.
Setting the current user ID on anonymous login fixes this. An alternative would be to have `qc::auth` check the global session ID first.
=> filter_authenticate bugfix

doc/response_api.md, tcl/response.tcl
Noticed that the Response API links were broken and have updated them. Also noticed that the namespace for `response actions` hadn't been updated to `response action` which would cause errors.
=> Doc links updated. actions > action

tcl/validate.tcl
`$name` is the name of the argument for the handler that may or may not be fully qualified i.e. `table.column` or `column`. The record was returned with the potentially fully qualified name of the argument which does not match up with the form elements and therefore was causing troubles with the validation plugin because it cannot select the input elements with a fully qualified name. The response should just return the column portion of a fully qualified name and this change fixes that.
The alternative is to have the validation plugin check if the name is fully qualified and split name by the separator `.`.
=> Use column instead of name for returned record response.

tcl/response.tcl
Checklist
----
- Setting record item invalid and checking the global variable `data` for `status` being present and set to `invalid`:
```tcl
> set data
set data
can't read "data": no such variable
> qc::response record invalid test "Foo" "Foo is invalid."
qc::response record invalid test "Foo" "Foo is invalid."
record {test {valid false value Foo message {Foo was invalid.}}} status invalid
> qc::data2json
qc::data2json
{
"status": "invalid",
"record": {
"test": {
"valid": false,
"value": "Foo",
"message": "Foo is invalid."
}
},
"message": {
},
"action": {
}
}
```
=> Set status to invalid when record invalid called.

tcl/cast.tcl
This is to make the following calls have the same result:
```
$ cast decimal 001
001.123
$ cast decimal -precision 10 001
1
```
After this change leading zeros will be stripped out and both will return ```1```
=> strip leading zeros

tcl/filter.tcl, tcl/register.tcl
- Ensure that registering works as before and also registers for authentication.
- Test `qc::registered` update too.
```tcl
> qc::register GET /foo
> qc::registered GET /foo
true
> qc::registered authenticate GET /foo
true
```
- Register method path without authentication
```
> qc::register -no-auth GET /foo
> qc::registered GET /foo
true
> qc::registered authenticate GET /foo
false
```
- Register a couple of paths. Update one to exempt it from authentication. Check that others are unaffected. 
```
> qc::register GET /foo
> qc::registered GET /foo
true
> qc::registered authenticate GET /foo
true
> qc::register GET /bar
> qc::registered GET /bar
true
> qc::registered authenticate GET /bar
true
> qc::register -no-auth GET /bar
> qc::registered GET /bar
true
> qc::registered authenticate GET …
```
=> no-auth flag added

tcl/handlers.tcl, tcl/response.tcl, tcl/validate.tcl
* Makes `qc::handlers validation data` consistent with `qc::handlers data` through use of new proc `qc::args_unambiguous`.
* Makes `message` arg for `qc::response record valid` optional.
Tested with new/update sales order in MLA ERP .
=> Make "qc::handlers validation data" consistent with "qc::handlers data"

tcl/url.tcl, test/url.test
@PeterChaplin Looks like you were using double colon for the port delimiter when it should be just a single colon. Think I've caught them all but could you have a look over to make sure?
=> Single colon for port

tcl/conn.tcl
For discussion.
If a wildcard character is passed in as part of the URL (and returned by ```qc::conn_path```), ```info procs``` behaves like ```string match``` and will return any matching proc.
So, ```info procs ::namespace::/*``` will return all procs defined in ```::namespace``` then will proceed to reference the wildcard as if ```::namespace::/*``` is the name of a proc.
I think it should only proceed if ```info procs``` returns exactly the name of the proc supplied, no more, no less.
=> Match 1 and only 1 proc

tcl/url.tcl, test/url.test
Reverts qcode-software/qcode-tcl#297
Introduces an url injection attack.
=> Revert "Allow qc::url to pick up local vars"

tcl/db_init.tcl, tcl/html.tcl, tcl/is.tcl, test/html.test
The xpath selectors for classes and IDs was using the `contains` function which will match anything that contains the given text. This is problematic in a lot of cases because CSS selectors do not work in this manner. The change made to use `css_selector2xpath` means that exact matching will be done on classes and IDs.
Tcl
----
- Checked `css_selector2xpath` to ensure it would generate correct xpath for the required CSS selectors:
- Elements
- Classes `.class1.class2`
- IDs `#ID`
- Pseduo selectors `:nth-child(*)`
- Combinations:
- `element.class1.class2`
- `#ID.class1.class2`
- `element#ID`
- `#ID > * > tr > td:nth-child(1)`
- HTML tests
- Ran `make test VERSION=6.46.1`
**Test HTML**
```tcl
set html {
<html>
<head>
<style type="text/css">
#table_1 > * > tr > td:nth-child(1) { …
```
=> Fix for ID and Class Matching

tcl/filter.tcl
**Tested on mla-erp**
Input:
```
https://qcode.dev.mlaccessories.co.uk/home.html?::testing=123
```
Log:
```
[03/May/2016:09:58:09][4005.7f2bd0507700][-conn:mla_erp:3-] App:Notice: Invalid form variable name: ::testing
```
Input:
```
https://qcode.dev.mlaccessories.co.uk/home.html?::testing=123&foo::bar=baz
```
Log:
```
[03/May/2016:10:00:57][4005.7f2bd0507700][-conn:mla_erp:3-] App:Notice: Invalid form variable name: ::testing
[03/May/2016:10:00:57][4005.7f2bd0507700][-conn:mla_erp:3-] App:Notice: Invalid form variable name: foo::bar
```
=> Log invalid form variable names

tcl/db_introspection.tcl
Tested on MLA ERP. `customer.nmbs_number` is a varchar with no length specified:
```
> qc::db_column_type customer nmbs_number
text
```
=> Treat Varchar With No Length As Text

tcl/form.tcl, tcl/handlers.tcl
See #383 
Tcl
----
All
---
**Form data**
```
account_name: testing
exchange_rate:1.61
duty_cost:0.00
freight_cost:0.00
stock_account_id:12
narration:
purchase_orders[]:12345
purchase_orders[]:67890
```
```
validate POST  /grn_new.tcl {
grn.stock_account_id
required.account_name
grn.exchange_rate
grn.narration
grn.duty_cost
grn.freight_cost
{form.purchase_orders {}}
} {
log $purchase_orders
...
}
```
**Log**
```
12345 67890
```
=> Remove Ending Square Brackets From Form Var Names

tcl/validate.tcl
Issue discovered when one field failed data validation, another field's valid flag was not being set because of this check: https://github.com/qcode-software/qcode-tcl/compare/validate2model-bug-fix2?expand=1#diff-5bbae3529ffd2733b2b7100ca589dd50L42
Valid flag is required for all fields
=> always initialise valid flag for each field in a record

tcl/is.tcl
Current Implementation
--------------------------------
| uri | 1st run in new interpreter | 2nd run in same interpreter |
| --- | --- | --- |
| https://foo.bar/baz?a=1 | 260,279 microseconds  | 273 microseconds|
| foo.bar/baz?a=1 | 275,685 microseconds | 258 microseconds |
| /foo.bar/baz?a=1 | 262,906 microseconds | 242 microseconds |
Updated Implementation
--------------------------------
| uri | 1st run in new interpreter | 2nd run in same interpreter |
| --- | --- | --- |
| https://foo.bar/baz?a=1 | 20,679 microseconds | 297 microseconds |
| foo.bar/baz?a=1 | 21,078 microseconds | 278 microseconds |
| /foo.bar/baz?a=1 | 22,803 microseconds | 265 microseconds |
=> refactor is uri to improve performance

tcl/response.tcl
The security issue with redirects is for open redirects based on user-supplied urls.
This change relaxes the constraint on redirect destinations but relies on the caller to sanitise the url destination.
https://portswigger.net/KnowledgeBase/issues/Details/00500100_Openredirection
=> Relax criteria for external domain redirect

tcl/db_introspection.tcl, tcl/tson.tcl, tcl/util_string.tcl
Test:
```tcl
qc::db_is json {{ "foo": "bar" }}
```
Output:
```
t
```
---
Test:
```tcl
qc::db_is json {{ "foo": bar }}
```
Output:
```
f
```
---
Test:
```tcl
qc::db_is int 24
```
Output:
```
t
```
---
Test:
```tcl
qc::db_is int foo
```
Output:
```
f
```
---
Test:
```tcl
qc::db_is plain_text foo
```
Output:
```
t
```
---
Test:
```tcl
qc::db_is plain_text <foo>
```
Output:
```
f
```
Test:
```tcl
qc::noun_indefinite_determiner object
```
Output:
```
an
```
---
Test:
```tcl
qc::noun_indefinite_determiner string
```
Output:
```
a
```
Test:
```tcl
qc::tson_string foo
```
Output:
```
string foo
```
---
Test:
```tcl
qc::tson_string null
```
Output:
```
string null
```
---
Test:
```tcl
qc::tson_string ""
```
Output:
```
string {}
```
---
Test:
```tcl
qc::tson_string 24
```
Output:
```
string 24
``` …
=> Tson constructors

tcl/db.tcl
Any code currently using db_pg_copy_load will need a re-write to use this.
=> Remove hard-coded database from db_pg_copy_load

tcl/email.tcl
While testing a project I received an error:
```
No file extension defined for mime type "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
```
This mime type is for Microsoft Office docx format as can be seen in this blog post from Microsoft:
https://blogs.msdn.microsoft.com/vsofficedeveloper/2008/05/08/office-2007-file-format-mime-types-for-http-content-streaming-2/
Testing
---
```tcl
qc::mime_type_guess "test.docx"
> application/vnd.openxmlformats-officedocument.wordprocessingml.document
```
```tcl
qc::mime_file_extension "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
> .docx
```
=> Added mime types for docx

tcl/filter.tcl
Filter to set up HTTP headers before the request handler is called. This is particularly useful for any files served by fastpath.
Testing
---
Tested on a project:
```tcl
ns_register_filter postauth $http_method /file-download/* qc::filter_set_headers content-disposition "attachment"
```
* Accessed a file in `/file-download/` path and inspected the response headers to ensure that the `content-disposition` header was set to `attachment`.
=> Filter to Set Up HTTP Headers

tcl/file.tcl
**Note: This is a breaking change due to the changing of arguments and removal of `qc::file_handler`**
The file structure to identify and create file caches is hard-coded which makes it impossible to use if the file structure is not the same as the hard-coded structure.
I've updated the file caching procs to accept a filepath as an argument. When refactoring this it became apparent that the request handler `qc::file_handler` was too trivial and therefore no longer necessary.
Testing
---
```tcl
set file_id 9227
set filepath "/home/nick/file/9227/9227.pdf"
qc::file_cache_exists $file_id $filepath
false
qc::file_cache_create $file_id $filepath
/home/nick/file/9227/9227.pdf
qc::file_cache_exists $file_id $filepath
true
qc::file_cache_data $file_id $filepath
url /home/nick/file/9227/9227.pdf …
```
=> File Changes

tcl/widget.tcl
It looks to me like the intention of `qc::widget` was to prioritise widget procs in the qcode-tcl library for creation and fall back to procs defined in the global namespace if no proc exists in the qcode-tcl library.
@bvw Do you recall if this was the intention?
If it was then it's currently bugged because the global namespace will never be checked. This is due to `info procs` checking for the given pattern in the _current_ namespace when no namespace is specified. Within `qc::widget` the current namespace is `::qc` therefore calling:
`info procs "widget_$type"` 
is exactly the same as calling:
`info procs "::qc::widget_$type"`
1. Locally installed a new version with the fix.
2. Created my own widget type in the global namespace that is not in the qcode-tcl library.
* `proc …
=> Widget Namespace Fix

test/cast.test, test/is.test, test/sql.test, test/url.test
revert changes introduced in https://github.com/qcode-software/qcode-tcl/pull/445.
SideNote: don't think the makefile testing works as expected when newer versions of qcode-tcl are installed. Think there is an existing GitHub issue relating to this.
I had to `make install VERSION=5.34.0` then `rm -rf /usr/lib/tcltck/qcode6*` then `make test VERSION=5.34.0` so that the version i was testing was actually the one I wanted to test.
=> revert changes to tcl tests for qcode-tcl-5

tcl/my.tcl
To avoid occasional hangs where ```exec``` will wait forever.
=> Use exec_proxy for qc::my commands

tcl/s3_tools.tcl
Authentication using EC2 instance IAM roles require a security token is sent with each request.
This implements that for the S3 API.
=> Utilise temporary sessions token when speaking to s3

tcl/html.tcl
Testing
---
Ran with HTML and single and grouped CSS selectors.
HTML for testing:
```html
<table id="table_1">
<thead>
<tr>
<th>Column 1</th>
</tr>
</thead>
<tbody>
<tr>
<td>Test</td>
</tr>
</tbody>
</table>
``` 
CSS for testing:
```css
#table_1 > * > tr > td:nth-child(1) {
background-color: #ece9d8;
}
#table_1 > thead > tr > th:nth-child(1), #table_1 > * > tr > td:nth-child(1) {
padding-left: 3px; padding-right: 3px;
}
```
Output:
```
qc::html_style2inline $html $css
<table id="table_1">
<thead>
<tr>
<th style="padding-left:3px;padding-right:3px">Column 1</th>
</tr>
</thead>
<tbody>
<tr>
<td style="background-color:#ece9d8;padding-left:3px;padding-right:3px">Test</td>
</tr>
</tbody>
</table>
```
=> Added support for grouped CSS selectors in html_style2inline

doc/tutorial-6-database.md
Originally throwing an error, this now matches the argument `person_id`  and therefore the column name.
=> Changed id to person_id in qc::url construction

tcl/args.tcl, tcl/bs_capsule.tcl, tcl/bs_form_layout.tcl, tcl/cast.tcl, tcl/castable.tcl, tcl/conn.tcl, tcl/is.tcl, test/cast.test, test/castable.test, test/is.test
Tested all existing qc::is_* and qc::cast_* procs still execute.
Run old tcl-tests against updated ```is``` & ```cast``` procs without error (except in the format of the return - eg. 1 vs true or 0 vs false)
=> Qcode 5 backporting

tcl/session.tcl
Bugfix for ```session_purge```
```extract(seconds from <interval>)``` returns the seconds component of the interval, and not the entire interval converted into seconds.
=> session_purge bugfix

tcl/ensemble_handlers.tcl
Always qcode-tcl data types using qcode-tcl validate/cast procs even when prefixed with db schema.
Ready for merge
=> always qcode-tcl data types using qcode-tcl validate/cast procs

tcl/ensemble_handlers.tcl
Always qcode-tcl data types using qcode-tcl validate/cast procs even when prefixed with db schema.
Ready for merge
=> Cast/Validate Bug Fix for qcode-tcl data types

tcl/handlers.tcl
=> Check for existence of arrays before attempting to obtain patterns

tcl/multimap.tcl
=> Added Optional Switches to multimap_exists

tcl/tabular_text.tcl, test/tabular_text.test
Adds `trim false` and `true` to columns conf.
E.G.
```tcl
lappend columns_conf [list label "Column A" var_name col_a trim false]
```
=> tabular_text_parse trim option - qcode-tcl-5

tcl/email.tcl, test/email.test
Allows email_header_values to cope with semicolons and escaped quotes within quoted values (such as filenames)
=> email_header_values enhancement

tcl/email.tcl, tcl/image_file.tcl
Testing
----
- Ran a local make-install and restarted mla-erp
- Used mla cp to run qc::image_file_convert on an image, converting to mime-type "image/webp"
=> Image file commit proc and support webp

tcl/cast.tcl, tcl/date.tcl, tcl/is.tcl, test/cast.test, test/castable.test, test/date.test, test/is.test
2019-11-31 is not a valid date, but we do cast it to 2019-12-01
Tcl accepts it as a date, postgresql does not.
=> Improve qc::is date

tcl/cast.tcl, tcl/castable.tcl, tcl/http.tcl, tcl/is.tcl, tcl/s3_tools.tcl, test/cast.test, test/castable.test, test/is.test, test/s3_tools.test
S3 subcommands have been updated to optionally use s3_url in place of bucket and remote_file (object_key)
qc::s3_url_bucket_object_key
qc::is s3_bucket
qc::is s3_object_key
qc::is s3_url
qc::cast s3_url
qc::castable s3_url
Testing of s3_tools procs in progress
is.test updated with is proc tests
=> s3_url is and cast procs & s3_tools updates

tcl/s3_tools.tcl
Bug caused by incorrect args for `qc::s3 upload` An `object_key` was being passed in where a `s3_location` was expected. 
Passed the qcode-tcl tests
Tested in DEV
=> Bug fix for s3 multipart upload

tcl/auth.tcl
Testing:
Performed local make-install, restarted erp, deleted browser cookies, navigated to login page, logged in.
=> Allow auth_check to use global session_id

tcl/param.tcl
param_get fails when called from the control port due to the ```is_dbconnected``` command returning false.
The ```_db``` global variable isn't set until the db has been accessed in that context
```
Welcome to erp running at /usr/lib/naviserver/bin/nsd (pid 3565)
NaviServer/4.99.19 for linux built on Jul  6 2020 at 16:06:38
Tag: tar-4.99.19
1> qc::db_connected
false
2> qc::param_get test
Don't know where your home directory is
3> db_1row {select * from users limit 1}
4> qc::db_connected
true
5> qc::param_get test
1
```
=> param_get failing in Naviserver cp - add case

tcl/image_cache.tcl, tcl/image_resize_task.tcl, test/image_cache.test, test/image_resize_task.test
Tcl
----
SQL
------
Testing
---
```
tclsh image_cache.test
image_cache.test:	Total	6	Passed	6	Skipped	0	Failed	0
```
```
tclsh image_resize_task.test
image_resize_task.test:	Total	3	Passed	3	Skipped	0	Failed	0
```
```
tclsh all.tcl
Tests located in:  /home/nick/qcode-tcl/test
Tests running in:  /home/nick/qcode-tcl/test
Temporary files stored in /home/nick/qcode-tcl/test
Tests began at Fri Feb 05 13:00:38 GMT 2021
_s3.test
args.test
auth.test
binary_convert.test
cast.test
castable.test
check.test
conn.test
conn_location.test
cookie.test
crypt.test
css_selector2xpath.test
csv.test
date.test …
```
=> Option To Check Image Resize Queue When Calling qc::image_data

tcl/db.tcl, tcl/image_cache.tcl, tcl/image_resize_task.tcl, test/db.test, test/image_cache.test, test/image_resize_task.test
Tcl
----
SQL
------
Testing
---
```
tclsh image_resize_task.test
image_resize_task.test:	Total	1	Passed	1	Skipped	0	Failed	0
```
```
tclsh image_cache.test
image_cache.test:	Total	3	Passed	3	Skipped	0	Failed	0
```
```
tclsh all.tcl
Tests located in:  /home/nick/qcode-tcl/test
Tests running in:  /home/nick/qcode-tcl/test
Temporary files stored in /home/nick/qcode-tcl/test
Tests began at Fri Feb 12 13:59:17 GMT 2021
_s3.test
args.test
auth.test
binary_convert.test
cast.test
castable.test
check.test
conn.test
conn_location.test
cookie.test
crypt.test
css_selector2xpath.test
csv.test
date.test …
```
=> Image Data & Image Resize Task Updates

tcl/aws.tcl
Tested on DEV control port by loading proc definition and running `qc::aws_credentials_set_from_ec2_role` via erp control port, examining `::env(AWS_ACCESS_KEY`, `::env(AWS_SECRET_ACCESS_KEY)`, and `::evn(AWS_SESSION_TOKEN)`, comparing to results of `qc::aws_metadata iam/security-credentials/MLA-DEV`
=> Remove dependency on json package by using tson

tcl/tabular_text.tcl, test/tabular_text.test
When merging consecutive white-spaces the final whitespace is always merged into the penultimate one.
This fixes that behaviour so that this only happens if the final whitespace is actually consecutive 
Added test and ran exiting tests
=> Fix for the final separator being merged into the penultimate one

tcl/conn.tcl, test/conn_host.test, test/conn_location.test, test/conn_port.test, test/conn_protocol.test
* Integrate mock-ns package into tests
* Add tests for conn_port conn_host and conn_protocol
* ```conn_protocol``` returns connection protocol unless ```X-Forwarded-Proto``` is set
* ```conn_port``` returns in the following precedence:
*  ```X-Forwarded-Port``` if set and numeric
* Legacy ```Port``` header if present
* Port portion of the ```Host``` header
* Default port 80 or 443 based on protocol
* ```conn_host``` returns Host header unless not present whereupon (legacy) it returns the host portion of ```ns_conn location```
* ```conn_location``` uses the above 3 procs to build location (exception to handle legacy cases where port will not be in ```Host``` header)
=> Conn location

tcl/db_init.tcl, tcl/db_introspection.tcl, test/db_introspection.test, test/db_setup.tcl
Support running DB tests on RDS instance
```
Tests ended at Mon Feb 07 16:40:53 GMT 2022
all.tcl:	Total	1757	Passed	1744	Skipped	13	Failed	0
12	knownBug
Total	1757	Passed	1744	Skipped	13	Failed	0
```
=> Add check for RDS superuser

tcl/tabular_text.tcl
Updates tabular_text_parse error message to not use the null character
Passed the qcode-tcl test for tabular_text_parse
Tested in the control port with ERP invoice parsers
=> Update error message in tabular_text_parse

tcl/_s3.tcl, tcl/http.tcl, tcl/s3.tcl, test/http.test
Rather than ```s3 get``` using a 2-step verification of file md5 (vulnerable to race conditions), move the logic into ```_s3_save``` where we use the ```http_save``` response headers to check md5 value in a single step.
Warn if we cannot check md5.
http_save tests would be better with mock responses but using httpbin as an interim.
```
Total	1823	Passed	1810	Skipped	13	Failed	0
```
=> S3 save update

tcl/db_introspection.tcl, tcl/validate.tcl, test/db_introspection.test, test/validate.test
The new `qc::db_table_check_constraints_*` procs are more efficient than making multiple calls to `qc::db_column_constraints` and `qc::db_eval_column_constraints` due to reducing database queries for fetching check constraints (1 per table instead of 1 per column) and using only the necessary args for evaluating each check constraint.
&nbsp; | First Run (s) | Subsequent Runs (s)
-|-|-
**Old** | 0.2 | 0.006
**New** | 0.17 | 0.005
&nbsp; | First Run (s) | Subsequent Runs (s)
-|-|-
**Old** | 3.87 | 1.86
**New** | 2.04 | 0.07
```
tclsh db_introspection.test
db_introspection.test:	Total	58	Passed	58	Skipped	0	Failed	0
tclsh validate.test
validate.test:	Total	3	Passed	3	Skipped	0	Failed	0
```
=> New Procs for Getting & Evaluating Database Table Check Constraints

tcl/aws_s3_ls.tcl, tcl/aws_s3_rest_api.tcl, test/aws_s3_ls.test, test/aws_s3_rest_api.test
Add ability to change http_get timeout when calling ```qc::aws s3 ls```
```
Tests ended at Wed Mar 08 10:36:49 GMT 2023
all.tcl:	Total	1864	Passed	1851	Skipped	13	Failed	0
Sourced 81 Test Files.
12	knownBug
Total	1864	Passed	1851	Skipped	13	Failed	0
Sourced 81 Test Files.
```
=> add timeout to aws s3 http_get

tcl/http.tcl, test/http.test
--------------
(MINOR)
Description
--------------
Extend http_put to return response code and headers in the same way as http_post
Test Results
--------------
```
Total	1882	Passed	1869	Skipped	13	Failed	0
Sourced 83 Test Files.
```
=> Add response code return to http_put + tests

tcl/_s3.tcl, test/s3.test
Board Ticket #
--------------
https://github.com/qcode-software/qcode/issues/58
--------------
(MINOR)
Description
--------------
The S3 REST API currently defaults to using HTTP which isn't secure. This update makes the existing API use HTTPS for all S3 API calls.
Test Results
--------------
```
tclsh test/all.tcl
Tests located in:  /home/nick/qcode-tcl/test
Tests running in:  /home/nick/qcode-tcl
Temporary files stored in /home/nick/qcode-tcl
Tests began at Thu Jun 22 17:46:28 BST 2023
_s3.test
args.test
auth.test
aws.test
aws_s3_ls.test …
```
=> Use HTTPS for S3 REST API calls

tcl/reload.tcl
Board Ticket #
--------------
[Refactor tlc/erp tlc/www tlc/lib to comply with linter. #7712](https://github.com/qcode-software/tlc/issues/7712)
--------------
(MINOR)
Description
--------------
Update qc::reload to use fileutil::findByPattern
Test Results
--------------
=> Update qc::reload to use fileutil::findByPattern

tcl/handlers.tcl
Board Ticket #
--------------
https://github.com/qcode-software/tlc/issues/7634
--------------
(MINOR)
Description
--------------
Raise INVALID_REQUEST error code when form variables are missing ... error handlers can when be adapated to supresses INVALID_REQUST errors and return user feedback instead of Software Bugs if desired.
Test Results
--------------
=> INVALID_REQUEST when missing form vars

tcl/handlers.tcl
Board Ticket #
--------------
--------------
(MINOR)
Description
--------------
Regular handlers throw an `INVALID_REQUEST` error code when args are missing. This change makes the validation handler call throw the same error code.
Test Results
--------------
=> Throw INVALID_REQUEST Error If Missing Args on Validation Call

tcl/conn.tcl, test/conn_remote_ip.test
Board Ticket #
--------------
* https://github.com/qcode-software/tlc/issues/8971
--------------
(MINOR)
Description
--------------
Since Naviserver has been updated to handle X-Forwarded-For headers in reverseproxy mode all that conn_remote_ip needs to do is return the ```ns_conn peeraddr``` result.
Open to discussion.
Test Results
--------------
```
Total   1888    Passed  1875    Skipped 13      Failed  0
Sourced 86 Test Files.
```
=> downscale what conn_remote_ip does

tcl/db_file.tcl, test/db_file.test, test/db_file_setup.tcl
Board Ticket #
--------------
https://github.com/qcode-software/mla/issues/6192
--------------
(MINOR)
Description
--------------
Add encryption to qc::db_file_insert, qc::db_file_copy and qc::db_file_export
Test Results
--------------
=> Add encryption to qc::db_file_insert, qc::db_file_copy and qc::db_file_export
